baseURL = 'https://mtteo.dev/'
title = "mtteo.eth"
theme= 'hugo-coder'
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "mtteo.eth"
  info = "rust, cryptography, ethereum, decentralization"
  description = "rust, cryptography, ethereum, decentralization"
  keywords = "blog,developer,personal"
  avatarurl = "/images/avatar.jpeg"

  faviconSVG = "images/favicon.ico"

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/MatteoMer/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/Matteo_Mer/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "Reading List"
  weight = 1
  url = "reading-list/"
